CREATE TABLE IF NOT EXISTS questions (
    id       BIGSERIAL    PRIMARY KEY,
    text_en  TEXT         NOT NULL,
    text_ru  TEXT         NOT NULL,
    category VARCHAR(64)  NOT NULL DEFAULT 'general'
);

INSERT INTO questions (text_en, text_ru, category) VALUES

-- habits
('Who among you sleeps the most?', 'Кто из вас больше всех спит?', 'habits'),
('Who among you stays up the latest?', 'Кто из вас позже всех ложится спать?', 'habits'),
('Who among you hits the snooze button the most?', 'Кто из вас чаще всего откладывает будильник?', 'habits'),
('Who among you is the biggest morning person?', 'Кто из вас самый жаворонок?', 'habits'),
('Who among you is the biggest night owl?', 'Кто из вас самая настоящая сова?', 'habits'),
('Who among you naps the most?', 'Кто из вас чаще всего дремлет?', 'habits'),
('Who among you snores the loudest?', 'Кто из вас громче всех храпит?', 'habits'),
('Who among you has the messiest room?', 'У кого из вас самая грязная комната?', 'habits'),
('Who among you is the most organized?', 'Кто из вас самый организованный?', 'habits'),
('Who among you takes the longest showers?', 'Кто из вас дольше всех принимает душ?', 'habits'),
('Who among you takes the longest to get ready?', 'Кто из вас дольше всех собирается?', 'habits'),
('Who among you is always late?', 'Кто из вас всегда опаздывает?', 'habits'),
('Who among you is always early?', 'Кто из вас всегда приходит заранее?', 'habits'),
('Who among you is the biggest couch potato?', 'Кто из вас самый лежебока?', 'habits'),
('Who among you wastes the most time?', 'Кто из вас больше всех тратит время впустую?', 'habits'),
('Who among you checks their phone first thing in the morning?', 'Кто из вас первым делом проверяет телефон утром?', 'habits'),
('Who among you forgets to drink water the most?', 'Кто из вас чаще всего забывает пить воду?', 'habits'),
('Who among you has the most chaotic schedule?', 'У кого из вас самый хаотичный распорядок дня?', 'habits'),
('Who among you wakes up without an alarm?', 'Кто из вас просыпается сам без будильника?', 'habits'),
('Who among you sleeps through every alarm?', 'Кто из вас засыпает сквозь все будильники?', 'habits'),
('Who among you does laundry the least often?', 'Кто из вас реже всех стирает одежду?', 'habits'),
('Who among you is the slowest eater?', 'Кто из вас ест медленнее всех?', 'habits'),
('Who among you is the fastest eater?', 'Кто из вас ест быстрее всех?', 'habits'),
('Who among you cleans most often?', 'Кто из вас убирается чаще всего?', 'habits'),
('Who among you is the biggest homebody?', 'Кто из вас самый домосед?', 'habits'),
('Who among you is hardest to wake up in the morning?', 'Кого из вас сложнее всего разбудить с утра?', 'habits'),
('Who among you bites their nails the most?', 'Кто из вас чаще всего грызет ногти?', 'habits'),
('Who among you is the most superstitious?', 'Кто из вас самый суеверный?', 'habits'),
('Who among you talks to themselves the most?', 'Кто из вас чаще всего говорит сам с собой?', 'habits'),
('Who among you leaves the most dirty dishes?', 'Кто из вас оставляет больше всего грязной посуды?', 'habits'),
('Who among you spends the most time on grooming?', 'Кто из вас больше всего времени тратит на уход за собой?', 'habits'),
('Who among you is most paranoid about germs?', 'Кто из вас самый параноик по поводу микробов?', 'habits'),

-- food
('Who among you eats the most?', 'Кто из вас больше всех ест?', 'food'),
('Who among you is the pickiest eater?', 'Кто из вас самый привередливый в еде?', 'food'),
('Who among you is the best cook?', 'Кто из вас лучше всех готовит?', 'food'),
('Who among you drinks the most coffee?', 'Кто из вас больше всех пьёт кофе?', 'food'),
('Who among you eats the most junk food?', 'Кто из вас больше всех ест вредную еду?', 'food'),
('Who among you would survive the longest without eating?', 'Кто из вас дольше всех продержится без еды?', 'food'),
('Who among you eats the spiciest food?', 'Кто из вас ест самую острую еду?', 'food'),
('Who among you would be the best barista?', 'Кто из вас был бы лучшим бариста?', 'food'),
('Who among you eats the strangest food combinations?', 'Кто из вас ест самые странные сочетания еды?', 'food'),
('Who among you would win a hot dog eating contest?', 'Кто из вас выиграл бы соревнование по поеданию хот-догов?', 'food'),
('Who among you is most likely to become a chef?', 'Кто из вас, скорее всего, станет шеф-поваром?', 'food'),
('Who among you always steals food from others'' plates?', 'Кто из вас всегда таскает еду с чужих тарелок?', 'food'),
('Who among you eats the most sweets?', 'Кто из вас ест больше всех сладкого?', 'food'),
('Who among you would go vegan first?', 'Кто из вас первым станет веганом?', 'food'),
('Who among you loves fast food the most?', 'Кто из вас больше всех любит фастфуд?', 'food'),
('Who among you snacks the most late at night?', 'Кто из вас чаще всего перекусывает ночью?', 'food'),
('Who among you would win a baking competition?', 'Кто из вас выиграл бы в соревновании по выпечке?', 'food'),
('Who among you hates vegetables the most?', 'Кто из вас больше всех ненавидит овощи?', 'food'),
('Who among you is the most adventurous eater?', 'Кто из вас смелее всех пробует новую еду?', 'food'),
('Who among you would eat anything for money?', 'Кто из вас съел бы что угодно ради денег?', 'food'),
('Who among you is the biggest food photographer?', 'Кто из вас чаще всего фотографирует еду?', 'food'),
('Who among you drinks the most tea?', 'Кто из вас пьёт больше всех чай?', 'food'),
('Who among you cooks the least?', 'Кто из вас реже всех готовит?', 'food'),
('Who among you would survive on takeout forever?', 'Кто из вас мог бы жить на доставке вечно?', 'food'),
('Who among you skips breakfast most often?', 'Кто из вас чаще всего пропускает завтрак?', 'food'),

-- education
('Who among you is the best student?', 'Кто из вас лучший студент?', 'education'),
('Who among you cheated the most on exams?', 'Кто из вас больше всех списывал на экзаменах?', 'education'),
('Who among you would go back to school?', 'Кто из вас хотел бы вернуться в школу?', 'education'),

-- alcohol
('Who among you gets drunk the fastest?', 'Кто из вас напивается быстрее всех?', 'alcohol'),
('Who among you drinks the most alcohol?', 'Кто из вас больше пьет алкоголь?', 'alcohol'),

-- music
('Who among you has the worst music taste?', 'Кто из вас имеет наихудший музыкальный вкус?', 'music'),
('Who among you would be the best singer?', 'Кто из вас был бы лучшим певцом?', 'music'),

-- personality
('Who among you is the loudest?', 'Кто из вас самый громкий?', 'personality'),
('Who among you is the most dramatic?', 'Кто из вас самый драматичный?', 'personality'),
('Who among you is the most competitive?', 'Кто из вас самый соревновательный?', 'personality'),
('Who among you is the most stubborn?', 'Кто из вас самый упрямый?', 'personality'),
('Who among you is the biggest procrastinator?', 'Кто из вас самый большой прокрастинатор?', 'personality'),
('Who among you cries the most easily?', 'Кто из вас плачет легче всего?', 'personality'),
('Who among you laughs the loudest?', 'Кто из вас громче всех смеётся?', 'personality'),
('Who among you is the most optimistic?', 'Кто из вас самый оптимистичный?', 'personality'),
('Who among you is the most stylish?', 'Кто из вас наиболее стильный?', 'personality'),
('Who among you is the most beautiful?', 'Кто из вас наиболее красивый?', 'personality'),
('Who among you worries the most?', 'Кто из вас больше всех переживает?', 'personality'),
('Who among you is the most adventurous?', 'Кто из вас самый авантюрный?', 'personality'),
('Who among you is the biggest introvert?', 'Кто из вас самый большой интроверт?', 'personality'),
('Who among you talks the most?', 'Кто из вас больше всех говорит?', 'personality'),
('Who among you is the most sarcastic?', 'Кто из вас самый саркастичный?', 'personality'),
('Who among you has the best sense of humor?', 'У кого из вас лучшее чувство юмора?', 'personality'),
('Who among you is the most forgetful?', 'Кто из вас самый забывчивый?', 'personality'),
('Who among you is the most patient?', 'Кто из вас самый терпеливый?', 'personality'),
('Who among you is the most impatient?', 'Кто из вас самый нетерпеливый?', 'personality'),
('Who among you is the most empathetic?', 'Кто из вас самый чуткий?', 'personality'),
('Who among you gets angry the fastest?', 'Кто из вас быстрее всех злится?', 'personality'),
('Who among you is the most mysterious?', 'Кто из вас самый загадочный?', 'personality'),
('Who among you is the most impulsive?', 'Кто из вас самый импульсивный?', 'personality'),
('Who among you is the most logical?', 'Кто из вас самый логичный?', 'personality'),
('Who among you overthinks everything?', 'Кто из вас думает обо всём слишком много?', 'personality'),
('Who among you is the biggest perfectionist?', 'Кто из вас самый перфекционист?', 'personality'),
('Who among you is the most laid-back?', 'Кто из вас самый расслабленный?', 'personality'),
('Who among you is the hardest to offend?', 'Кого из вас сложнее всего обидеть?', 'personality'),
('Who among you is the most easily embarrassed?', 'Кто из вас легче всего смущается?', 'personality'),
('Who among you is the biggest risk-taker?', 'Кто из вас самый большой любитель рисковать?', 'personality'),
('Who among you is the most gullible?', 'Кто из вас самый доверчивый?', 'personality'),
('Who among you has the worst poker face?', 'У кого из вас хуже всего покерфейс?', 'personality'),
('Who among you has the best skincare routine?', 'У кого из вас лучший уход за кожей?', 'personality'),
('Who among you would never leave the house without makeup?', 'Кто из вас никогда не выйдет из дома без макияжа?', 'personality'),
('Who among you is the strongest?', 'Кто из вас самый сильный?', 'personality'),
('Who among you is the shortest?', 'Кто из вас самый низкий?', 'personality'),
('Who among you is the tallest?', 'Кто из вас самый высокий?', 'personality'),
('Who among you has the best body?', 'У кого из вас лучшее тело?', 'personality'),
('Who among you follows fashion trends the most?', 'Кто из вас больше всего следит за модными трендами?', 'personality'),
('Who among you has the most clothing?', 'У кого из вас больше всего одежды?', 'personality'),
('Who among you would wear anything without caring?', 'Кто из вас носил бы что угодно не заботясь о внешнем виде?', 'personality'),

-- social
('Who among you is the most social?', 'Кто из вас самый общительный?', 'social'),
('Who among you makes friends the fastest?', 'Кто из вас быстрее всех заводит друзей?', 'social'),
('Who among you is always the life of the party?', 'Кто из вас всегда душа компании?', 'social'),
('Who among you gives the best advice?', 'Кто из вас даёт лучшие советы?', 'social'),
('Who among you is the biggest gossip?', 'Кто из вас больше всех сплетничает?', 'social'),
('Who among you would talk to a stranger first?', 'Кто из вас первым заговорит с незнакомцем?', 'social'),
('Who among you would win a debate?', 'Кто из вас выиграл бы дебаты?', 'social'),
('Who among you is the best at keeping secrets?', 'Кто из вас лучше всех хранит секреты?', 'social'),
('Who among you would cry at a wedding?', 'Кто из вас заплачет на свадьбе?', 'social'),
('Who among you is the best mediator in conflicts?', 'Кто из вас лучший миротворец в конфликтах?', 'social'),
('Who among you would be the best therapist?', 'Кто из вас был бы лучшим психотерапевтом?', 'social'),
('Who among you has the most charisma?', 'У кого из вас больше всего харизмы?', 'social'),
('Who among you would be the best public speaker?', 'Кто из вас был бы лучшим публичным оратором?', 'social'),
('Who among you cancels plans the most?', 'Кто из вас чаще всего отменяет планы?', 'social'),
('Who among you never cancels plans?', 'Кто из вас никогда не отменяет планы?', 'social'),
('Who among you would be the most fun at a party?', 'Кто из вас был бы веселее всех на вечеринке?', 'social'),
('Who among you would leave a party first?', 'Кто из вас первым уйдёт с вечеринки?', 'social'),
('Who among you would make the best influencer?', 'Кто из вас был бы лучшим инфлюенсером?', 'social'),
('Who among you is the best listener?', 'Кто из вас лучше всех слушает?', 'social'),
('Who among you would cause the most drama?', 'Кто из вас устроит больше всех драму?', 'social'),
('Who among you watches TikTok the most?', 'Кто из вас больше всех смотрит тик ток?', 'social'),
('Who among you shares TikTok videos the most?', 'Кто из вас больше всех скидывает тик токи?', 'social'),
('Who among you lifts the mood the most?', 'Кто из вас лучше всех поднимает настроение?', 'social'),
('Who among you is more annoying when in a bad mood?', 'Кто из вас более раздражающий когда в плохом настроении?', 'social'),
('Who among you is the best at conflict resolution?', 'Кто из вас лучше всех разрешает конфликты?', 'social'),
('Who among you runs away from conflict?', 'Кто из вас убегает от конфликтов?', 'social'),
('Who among you always starts arguments?', 'Кто из вас всегда затевает ссоры?', 'social'),

-- money
('Who among you spends the most money?', 'Кто из вас больше всех тратит деньги?', 'money'),
('Who among you is the most frugal?', 'Кто из вас самый экономный?', 'money'),
('Who among you shops the most?', 'Кто из вас больше всех ходит по магазинам?', 'money'),
('Who among you would win a negotiation?', 'Кто из вас выиграл бы переговоры?', 'money'),
('Who among you would earn the most money?', 'Кто из вас заработал бы больше всех?', 'money'),
('Who among you is most likely to forget their wallet?', 'Кто из вас, скорее всего, забудет кошелёк?', 'money'),
('Who among you is the most generous?', 'Кто из вас самый щедрый?', 'money'),
('Who among you would blow their salary in a day?', 'Кто из вас потратил бы всю зарплату за день?', 'money'),
('Who among you is best at saving money?', 'Кто из вас лучше всех умеет копить?', 'money'),
('Who among you buys the most unnecessary things?', 'Кто из вас покупает больше всего ненужных вещей?', 'money'),
('Who among you is most likely to invest in crypto?', 'Кто из вас, скорее всего, вложит деньги в крипту?', 'money'),
('Who among you would go bankrupt first?', 'Кто из вас обанкротится первым?', 'money'),
('Who among you always forgets to pay people back?', 'Кто из вас всегда забывает отдавать долги?', 'money'),
('Who among you is most likely to win the lottery?', 'Кто из вас, скорее всего, выиграет в лотерею?', 'money'),
('Who among you splurges the most on food delivery?', 'Кто из вас больше всех тратит на доставку еды?', 'money'),

-- technology
('Who among you spends the most time on their phone?', 'Кто из вас больше всех сидит в телефоне?', 'technology'),
('Who among you is the best gamer?', 'Кто из вас лучший геймер?', 'technology'),
('Who among you would survive the longest without internet?', 'Кто из вас дольше всех продержится без интернета?', 'technology'),
('Who among you is the most tech-savvy?', 'Кто из вас лучше всех разбирается в технологиях?', 'technology'),
('Who among you spends the most time on social media?', 'Кто из вас больше всех сидит в соцсетях?', 'technology'),
('Who among you would win a video game tournament?', 'Кто из вас выиграл бы турнир по видеоиграм?', 'technology'),
('Who among you takes the most photos?', 'Кто из вас делает больше всего фотографий?', 'technology'),
('Who among you binge-watches shows the most?', 'Кто из вас больше всех смотрит сериалы запоем?', 'technology'),
('Who among you would make the best content creator?', 'Кто из вас был бы лучшим контент-мейкером?', 'technology'),
('Who among you is most likely to break a new phone?', 'Кто из вас, скорее всего, разобьёт новый телефон?', 'technology'),
('Who among you uses the most streaming services?', 'Кто из вас пользуется наибольшим количеством стриминговых сервисов?', 'technology'),
('Who among you would fall for a tech scam?', 'Кто из вас, скорее всего, попадётся на интернет-мошенничество?', 'technology'),
('Who among you has the most apps on their phone?', 'У кого из вас больше всего приложений в телефоне?', 'technology'),
('Who among you is the worst at replying to messages?', 'Кто из вас хуже всех отвечает на сообщения?', 'technology'),
('Who among you has the most unread notifications?', 'У кого из вас больше всего непрочитанных уведомлений?', 'technology'),
('Who among you would make the best hacker?', 'Кто из вас мог бы стать лучшим хакером?', 'technology'),
('Who among you most often forgets to charge their phone?', 'Кто из вас чаще всего забывает зарядить телефон?', 'technology'),
('Who among you has the oldest device?', 'У кого из вас самое старое устройство?', 'technology'),
('Who among you would create a viral video?', 'Кто из вас снял бы вирусное видео?', 'technology'),
('Who among you reads the most online?', 'Кто из вас больше всех читает в интернете?', 'technology'),

-- travel
('Who among you travels the most?', 'Кто из вас больше всех путешествует?', 'travel'),
('Who among you would survive best in the wilderness?', 'Кто из вас лучше всех выживет в дикой природе?', 'travel'),
('Who among you is most afraid of flying?', 'Кто из вас больше всех боится летать?', 'travel'),
('Who among you would move to another country?', 'Кто из вас переедет в другую страну?', 'travel'),
('Who among you gets lost the most easily?', 'Кто из вас чаще всего теряется?', 'travel'),
('Who among you packs the most luggage?', 'Кто из вас берёт больше всего багажа?', 'travel'),
('Who among you is most likely to go on a spontaneous trip?', 'Кто из вас, скорее всего, уедет в спонтанное путешествие?', 'travel'),
('Who among you would go skydiving first?', 'Кто из вас первым прыгнет с парашютом?', 'travel'),
('Who among you is the best navigator?', 'Кто из вас лучший навигатор?', 'travel'),
('Who among you always loses their luggage?', 'Кто из вас всегда теряет багаж?', 'travel'),
('Who among you would visit the most countries?', 'Кто из вас объездит больше всего стран?', 'travel'),
('Who among you is most likely to get sunburnt?', 'Кто из вас, скорее всего, сгорит на солнце?', 'travel'),
('Who among you would be the worst travel companion?', 'Кто из вас был бы худшим попутчиком?', 'travel'),
('Who among you always forgets to pack something?', 'Кто из вас всегда что-то забывает собрать в дорогу?', 'travel'),
('Who among you sleeps best on planes?', 'Кто из вас лучше всех спит в самолёте?', 'travel'),
('Who among you would go camping first?', 'Кто из вас первым отправится в кемпинг?', 'travel'),
('Who among you would be the best tour guide?', 'Кто из вас был бы лучшим экскурсоводом?', 'travel'),
('Who among you complains most on long trips?', 'Кто из вас больше всех жалуется в длинных поездках?', 'travel'),
('Who among you is the most adventurous abroad?', 'Кто из вас самый авантюрный за границей?', 'travel'),
('Who among you would hitchhike across the country?', 'Кто из вас поедет автостопом через всю страну?', 'travel'),

-- work
('Who among you is the biggest workaholic?', 'Кто из вас самый трудоголик?', 'work'),
('Who among you procrastinates the most at work?', 'Кто из вас больше всех откладывает работу на потом?', 'work'),
('Who among you would be the best boss?', 'Кто из вас был бы лучшим начальником?', 'work'),
('Who among you would be the worst boss?', 'Кто из вас был бы худшим начальником?', 'work'),
('Who among you is most likely to become famous?', 'Кто из вас, скорее всего, станет знаменитым?', 'work'),
('Who among you would quit their job first?', 'Кто из вас первым уволится с работы?', 'work'),
('Who among you would start a business first?', 'Кто из вас первым откроет свой бизнес?', 'work'),
('Who among you is the most creative?', 'Кто из вас самый творческий?', 'work'),
('Who among you is the best problem solver?', 'Кто из вас лучше всех решает проблемы?', 'work'),
('Who among you is most likely to become a millionaire?', 'Кто из вас, скорее всего, станет миллионером?', 'work'),
('Who among you would get promoted the fastest?', 'Кто из вас получит повышение быстрее всех?', 'work'),
('Who among you would get away with doing the least work?', 'Кто из вас меньше всех работал бы и остался незамеченным?', 'work'),
('Who among you would be fired first?', 'Кого из вас уволят первым?', 'work'),
('Who among you is the most productive?', 'Кто из вас самый продуктивный?', 'work'),
('Who among you takes the longest lunch breaks?', 'Кто из вас берёт самые длинные обеденные перерывы?', 'work'),
('Who among you would be the best salesperson?', 'Кто из вас был бы лучшим продавцом?', 'work'),
('Who among you works the most overtime?', 'Кто из вас больше всех перерабатывает?', 'work'),
('Who among you is most likely to work remotely from a beach?', 'Кто из вас, скорее всего, будет работать удалённо с пляжа?', 'work'),
('Who among you has the most side hustles?', 'У кого из вас больше всего подработок?', 'work'),
('Who among you is best at meeting deadlines?', 'Кто из вас лучше всех соблюдает дедлайны?', 'work'),

-- skills
('Who among you is the best singer?', 'Кто из вас лучше всех поёт?', 'skills'),
('Who among you is the best dancer?', 'Кто из вас лучше всех танцует?', 'skills'),
('Who among you is the best artist?', 'Кто из вас лучший художник?', 'skills'),
('Who among you has the best memory?', 'У кого из вас лучшая память?', 'skills'),
('Who among you is the best driver?', 'Кто из вас лучший водитель?', 'skills'),
('Who among you is the most athletic?', 'Кто из вас самый спортивный?', 'skills'),
('Who among you would win a trivia contest?', 'Кто из вас выиграл бы в викторине?', 'skills'),
('Who among you is the best writer?', 'Кто из вас лучший писатель?', 'skills'),
('Who among you learns new languages the fastest?', 'Кто из вас быстрее всех учит языки?', 'skills'),
('Who among you is the best at math?', 'Кто из вас лучше всех считает?', 'skills'),
('Who among you tells the best stories?', 'Кто из вас рассказывает лучшие истории?', 'skills'),
('Who among you gives the best hugs?', 'Кто из вас лучше всех обнимается?', 'skills'),
('Who among you gives the best gifts?', 'Кто из вас дарит лучшие подарки?', 'skills'),
('Who among you stays the calmest under pressure?', 'Кто из вас лучше всех сохраняет спокойствие под давлением?', 'skills'),
('Who among you is the best at fixing things?', 'Кто из вас лучше всех чинит вещи?', 'skills'),
('Who among you would win a chess game?', 'Кто из вас выиграл бы в шахматы?', 'skills'),
('Who among you would win an arm wrestling match?', 'Кто из вас выиграл бы в армрестлинге?', 'skills'),
('Who among you always wins at rock-paper-scissors?', 'Кто из вас всегда побеждает в «камень-ножницы-бумага»?', 'skills'),
('Who among you is the best photographer?', 'Кто из вас лучший фотограф?', 'skills'),
('Who among you is best at doing impressions?', 'Кто из вас лучше всех копирует других?', 'skills'),
('Who among you tells the best jokes?', 'Кто из вас лучше шутит?', 'skills'),
('Who among you is the best at video games?', 'Кто из вас лучше играет в компьютерные игры?', 'skills'),
('Who among you is the best at board games?', 'Кто из вас лучше играет в настольные игры?', 'skills'),

-- driving
('Who among you is the most aggressive driver?', 'Кто из вас самый агрессивный водитель?', 'driving'),
('Who among you drives the slowest?', 'Кто из вас медленнее всех ездит?', 'driving'),
('Who among you has gotten the most speeding tickets?', 'Кто из вас получил больше всего штрафов за превышение скорости?', 'driving'),

-- pets
('Who among you would be the best pet owner?', 'Кто из вас был бы лучшим хозяином домашних животных?', 'pets'),
('Who among you is most allergic to animals?', 'Кто из вас больше всех аллергичен на животных?', 'pets'),
('Who among you talks to their pet the most?', 'Кто из вас больше всего разговаривает со своим питомцем?', 'pets'),

-- fun
('Who among you is most likely to become a viral meme?', 'Кто из вас, скорее всего, станет мемом?', 'fun'),
('Who among you talks in their sleep?', 'Кто из вас говорит во сне?', 'fun'),
('Who among you would panic first in an emergency?', 'Кто из вас первым запаникует в экстренной ситуации?', 'fun'),
('Who among you would eat bugs for $1000?', 'Кто из вас съел бы жуков за 1000$?', 'fun'),
('Who among you would accidentally start a fire while cooking?', 'Кто из вас, скорее всего, случайно что-нибудь подожжёт на кухне?', 'fun'),
('Who among you would survive a zombie apocalypse?', 'Кто из вас выжил бы в зомби-апокалипсисе?', 'fun'),
('Who among you would be voted off first on a deserted island?', 'Кого из вас первым выгонят с необитаемого острова?', 'fun'),
('Who among you would win a staring contest?', 'Кто из вас выиграл бы в гляделки?', 'fun'),
('Who among you has the weirdest hobby?', 'У кого из вас самое странное хобби?', 'fun'),
('Who among you is most likely to believe in conspiracy theories?', 'Кто из вас, скорее всего, верит в теории заговора?', 'fun'),
('Who among you would be last to notice a spider in the room?', 'Кто из вас последним заметит паука в комнате?', 'fun'),
('Who among you would send a message to the wrong person?', 'Кто из вас, скорее всего, отправит сообщение не тому?', 'fun'),
('Who among you would forget their own birthday?', 'Кто из вас забудет собственный день рождения?', 'fun'),
('Who among you is most likely to trip in public?', 'Кто из вас, скорее всего, споткнётся и упадёт на людях?', 'fun'),
('Who among you would win a pillow fight?', 'Кто из вас выиграл бы в битве подушками?', 'fun'),
('Who among you is most likely to get a tattoo next?', 'Кто из вас, скорее всего, сделает следующую татуировку?', 'fun'),
('Who among you would end up in the news?', 'Кто из вас попадёт в новости?', 'fun'),
('Who among you is most likely to adopt 10 cats?', 'Кто из вас, скорее всего, заведёт 10 кошек?', 'fun'),
('Who among you sings the loudest in the shower?', 'Кто из вас громче всех поёт в душе?', 'fun'),
('Who among you cries the most during movies?', 'Кто из вас больше всех плачет во время фильмов?', 'fun'),
('Who among you would win a karaoke contest?', 'Кто из вас выиграл бы в конкурсе по карааоке?', 'fun'),
('Who among you has the most unusual fear?', 'У кого из вас самый необычный страх?', 'fun'),
('Who among you would be a terrible actor?', 'Кто из вас был бы ужасным актёром?', 'fun'),
('Who among you would win a dance-off?', 'Кто из вас выиграл бы танцевальный баттл?', 'fun'),
('Who among you is most likely to sleepwalk?', 'Кто из вас, скорее всего, ходит во сне?', 'fun'),
('Who among you would be the worst roommate?', 'Кто из вас был бы худшим соседом по комнате?', 'fun'),
('Who among you would win a spelling bee?', 'Кто из вас выиграл бы орфографический конкурс?', 'fun'),
('Who among you would say something awkward at the worst moment?', 'Кто из вас, скорее всего, скажет что-то неловкое не вовремя?', 'fun'),
('Who among you would be the best at improv comedy?', 'Кто из вас лучше всех справился бы с импровизационной комедией?', 'fun'),
('Who among you is most likely to cry from laughter?', 'Кто из вас, скорее всего, расплачется от смеха?', 'fun'),

-- fears
('Who among you is the most afraid of bugs?', 'Кто из вас больше всех боится насекомых?', 'fears'),
('Who among you is most afraid of the dark?', 'Кто из вас больше всех боится темноты?', 'fears'),
('Who among you would be too scared to ride a roller coaster?', 'Кто из вас побоится сесть на американские горки?', 'fears'),
('Who among you screams loudest during horror movies?', 'Кто из вас громче всех кричит во время ужастиков?', 'fears'),
('Who among you is most afraid of needles?', 'Кто из вас больше всех боится уколов?', 'fears'),
('Who among you is most afraid of clowns?', 'Кто из вас больше всех боится клоунов?', 'fears'),
('Who among you would refuse to bungee jump?', 'Кто из вас откажется прыгать с тарзанки?', 'fears'),
('Who among you is most afraid of public speaking?', 'Кто из вас больше всех боится выступать на публике?', 'fears'),
('Who among you would scream first in a haunted house?', 'Кто из вас первым закричит в доме с привидениями?', 'fears'),
('Who among you is most afraid of dentists?', 'Кто из вас больше всех боится стоматологов?', 'fears'),
('Who among you is most afraid of the ocean?', 'Кто из вас больше всех боится океана?', 'fears'),
('Who among you avoids all scary movies?', 'Кто из вас избегает всех фильмов ужасов?', 'fears'),
('Who among you would faint at the sight of blood?', 'Кто из вас упадёт в обморок от вида крови?', 'fears'),
('Who among you is most afraid of being alone?', 'Кто из вас больше всех боится одиночества?', 'fears'),
('Who among you would be scared by a tiny dog?', 'Кто из вас испугается маленькой собаки?', 'fears'),

-- relationships
('Who among you falls in love the fastest?', 'Кто из вас влюбляется быстрее всех?', 'relationships'),
('Who among you would be the best partner?', 'Кто из вас был бы лучшим партнёром?', 'relationships'),
('Who among you flirts the most?', 'Кто из вас больше всех флиртует?', 'relationships'),
('Who among you is the most loyal friend?', 'Кто из вас самый верный друг?', 'relationships'),
('Who among you would ghost someone first?', 'Кто из вас первым оставит кого-то без ответа?', 'relationships'),
('Who among you would settle down first?', 'Кто из вас первым создаст семью?', 'relationships'),
('Who among you would do the most for a friend?', 'Кто из вас сделает больше всего ради друга?', 'relationships'),
('Who among you has the most friends?', 'У кого из вас больше всего друзей?', 'relationships'),
('Who among you stays in touch with people the best?', 'Кто из вас лучше всех поддерживает связь с людьми?', 'relationships'),
('Who among you would be the most protective partner?', 'Кто из вас был бы самым защитным партнёром?', 'relationships'),
('Who among you is the most romantic?', 'Кто из вас самый романтичный?', 'relationships'),
('Who among you would plan the best date?', 'Кто из вас организует лучшее свидание?', 'relationships'),
('Who among you is most likely to slide into someone''s DMs?', 'Кто из вас, скорее всего, напишет кому-то в личку?', 'relationships'),
('Who among you would be the most jealous?', 'Кто из вас был бы самым ревнивым?', 'relationships'),
('Who among you forgives the fastest?', 'Кто из вас прощает быстрее всех?', 'relationships'),
('Who among you holds grudges the longest?', 'Кто из вас дольше всех обижается?', 'relationships'),
('Who among you is most likely to have a crush on a stranger?', 'Кто из вас, скорее всего, влюбится в незнакомца?', 'relationships'),
('Who among you would be the best parent?', 'Кто из вас был бы лучшим родителем?', 'relationships'),
('Who among you is most likely to find love online?', 'Кто из вас, скорее всего, найдёт любовь в интернете?', 'relationships'),
('Who among you is the hardest to read emotionally?', 'Кого из вас сложнее всего понять эмоционально?', 'relationships'),
('Who among you is the most honest?', 'Кто из вас более честный?', 'relationships'),
('Who among you lies the most?', 'Кто из вас больше врет?', 'relationships'),
('Who among you is the most caring?', 'Кто из вас более заботливый?', 'relationships'),
('Who among you is the most kind?', 'Кто из вас более добрый?', 'relationships'),

-- home
('Who among you has the nicest apartment?', 'У кого из вас самая красивая квартира?', 'home'),
('Who among you would renovate their place first?', 'Кто из вас первым отремонтирует своё жилье?', 'home'),
('Who among you has the best interior design?', 'У кого из вас лучший дизайн интерьера?', 'home'),

-- hobbies
('Who among you has the weirdest talent?', 'У кого из вас самый странный талант?', 'hobbies'),
('Who among you collects the most random stuff?', 'Кто из вас собирает больше всего случайных вещей?', 'hobbies'),
('Who among you would become a YouTuber?', 'Кто из вас стал бы ютубером?', 'hobbies'),

-- weather
('Who among you hates winter the most?', 'Кто из вас больше всех ненавидит зиму?', 'weather'),
('Who among you loves summer the most?', 'Кто из вас больше всех любит лето?', 'weather'),

-- health
('Who among you would last the longest in a plank challenge?', 'Кто из вас дольше всех простоит в планке?', 'health'),
('Who among you eats the healthiest?', 'Кто из вас питается правильнее всех?', 'health'),
('Who among you runs the fastest?', 'Кто из вас бегает быстрее всех?', 'health'),
('Who among you is worst at sticking to a diet?', 'Кто из вас хуже всех соблюдает диету?', 'health'),
('Who among you would win a yoga challenge?', 'Кто из вас выиграл бы в соревновании по йоге?', 'health'),
('Who among you goes to the gym the most?', 'Кто из вас чаще всего ходит в зал?', 'health'),
('Who among you has the most energy?', 'У кого из вас больше всего энергии?', 'health'),
('Who among you gets sick the most often?', 'Кто из вас болеет чаще всех?', 'health'),
('Who among you would last the longest in a marathon?', 'Кто из вас дольше всех продержится в марафоне?', 'health'),
('Who among you is the most flexible?', 'Кто из вас самый гибкий?', 'health'),
('Who among you recovers from illness the fastest?', 'Кто из вас быстрее всех выздоравливает?', 'health'),
('Who among you takes the most vitamins and supplements?', 'Кто из вас принимает больше всего витаминов?', 'health'),
('Who among you drinks the most water?', 'Кто из вас пьёт больше всего воды?', 'health'),
('Who among you has the best posture?', 'У кого из вас лучшая осанка?', 'health'),
('Who among you would win a swimming race?', 'Кто из вас выиграл бы в заплыве?', 'health'),

-- minecraft
('Who among you dies the most in Minecraft lava?', 'Кто из вас чаще всего умирает в лаве в Майнкрафте?', 'minecraft'),
('Who among you would find diamonds first in Minecraft?', 'Кто из вас первым найдёт алмазы в Майнкрафте?', 'minecraft'),
('Who among you is the best builder in Minecraft?', 'Кто из вас лучший строитель в Майнкрафте?', 'minecraft'),
('Who among you spends the most time mining in Minecraft?', 'Кто из вас больше всего времени проводит в шахте в Майнкрафте?', 'minecraft'),
('Who among you gets lost the most in Minecraft?', 'Кто из вас чаще всего теряется в Майнкрафте?', 'minecraft'),
('Who among you would beat the Ender Dragon first in Minecraft?', 'Кто из вас первым победит дракона Края в Майнкрафте?', 'minecraft'),
('Who among you would survive the longest in Minecraft Hardcore mode?', 'Кто из вас дольше всех выживет в хардкоре в Майнкрафте?', 'minecraft'),
('Who among you steals the most from shared chests in Minecraft?', 'Кто из вас чаще всего ворует из общих сундуков в Майнкрафте?', 'minecraft'),
('Who among you builds the ugliest houses in Minecraft?', 'Кто из вас строит самые некрасивые дома в Майнкрафте?', 'minecraft'),
('Who among you would accidentally hit a zombified piglin in Minecraft?', 'Кто из вас случайно ударит свино-зомби в Майнкрафте?', 'minecraft'),
('Who among you makes the biggest farms in Minecraft?', 'Кто из вас строит самые большие фермы в Майнкрафте?', 'minecraft'),
('Who among you always forgets to set spawn in Minecraft?', 'Кто из вас всегда забывает поставить точку спавна в Майнкрафте?', 'minecraft'),
('Who among you would become the richest player on a Minecraft server?', 'Кто из вас станет самым богатым игроком на сервере Майнкрафта?', 'minecraft'),
('Who among you rushes to the Nether too early in Minecraft?', 'Кто из вас слишком рано идёт в Незер в Майнкрафте?', 'minecraft'),
('Who among you would start the biggest war on a Minecraft server?', 'Кто из вас устроит самую большую войну на сервере Майнкрафта?', 'minecraft'),
('Who among you would build the biggest redstone machine in Minecraft?', 'Кто из вас построит самую большую редстоун-машину в Майнкрафте?', 'minecraft'),
('Who among you never finishes their builds in Minecraft?', 'Кто из вас никогда не заканчивает постройки в Майнкрафте?', 'minecraft'),
('Who among you always carries random junk in Minecraft?', 'Кто из вас всегда носит с собой бесполезный хлам в Майнкрафте?', 'minecraft'),
('Who among you would AFK at a farm the longest in Minecraft?', 'Кто из вас дольше всех будет стоять АФК на ферме в Майнкрафте?', 'minecraft'),
('Who among you is most likely to dig straight down in Minecraft?', 'Кто из вас, скорее всего, будет копать прямо вниз в Майнкрафте?', 'minecraft'),
('Who among you forgets coordinates the most in Minecraft?', 'Кто из вас чаще всего забывает координаты в Майнкрафте?', 'minecraft'),
('Who among you would build a secret base in Minecraft?', 'Кто из вас построит секретную базу в Майнкрафте?', 'minecraft'),
('Who among you spends the longest decorating their Minecraft house?', 'Кто из вас дольше всех украшает свой дом в Майнкрафте?', 'minecraft'),
('Who among you would lose all their items in Minecraft first?', 'Кто из вас первым потеряет весь инвентарь в Майнкрафте?', 'minecraft'),
('Who among you would accidentally blow up the base in Minecraft?', 'Кто из вас случайно взорвёт базу в Майнкрафте?', 'minecraft')
('Who among you is the best at PvP in Minecraft?', 'Кто из вас лучше всех в PvP в Майнкрафте?', 'minecraft'),
('Who among you is the best at mace PvP in Minecraft?', 'Кто из вас лучше всех в PvP на буловах в Майнкрафте?', 'minecraft'),
('Who among you is the best at crystal PvP in Minecraft?', 'Кто из вас лучше всех в PvP кристалами в Майнкрафте?', 'minecraft'),
('Who among you is the best at Minecraft speedruns?', 'Кто из вас лучше всех в спидранах в Майнкрафте?', 'minecraft'),
('Who among you watches Minecraft series the most?', 'Кто из вас больше всех смотрит Майнкрафт сериалы?', 'minecraft'),
('Who among you is most likely to get accepted onto the Freakland Minecraft server?', 'Кого из вас, скорее всего, возьмут на сервер Фрикленд в Майнкрафте?', 'minecraft');
